/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "js": {
      "key": "js",
      "scope": "tags",
      "path": "/tag/js/",
      "pageKeys": [
        "v-4af3b0ae",
        "v-0c208636",
        "v-5b3ce4be",
        "v-63fb3140",
        "v-f22bfeac"
      ]
    },
    "vue": {
      "key": "vue",
      "scope": "tags",
      "path": "/tag/vue/",
      "pageKeys": [
        "v-63fb3140",
        "v-f22bfeac"
      ]
    }
  },
  "categories": {},
  "timeline": {}
}