/**
 * Generated by "@vuepress/plugin-blog"
 */

import sorters from './pageSorters'
import filters from './pageFilters'

export default [{
  pid: "tags",
  id: "js",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/js/","interval":[0,5]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "vue",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/vue/","interval":[0,2]}],
  prevText: "Prev",
  nextText: "Next",
}]